### ISSUE TITLE
This hack doesn't seem to work on Yosemite

### ISSUE THREAD

**Issue by Quantumpanda** [tzvetkoff/adobe_case_sensitive_volumes#1]
I did a wipe-and-install to upgrade my MBP to Yosemite, and now I'm reinstalling everything. I switched my boot drive to case sensitive, because Unix. So of course, reinstalling CS6 failed.

I did some research and ran across your hack. I followed all the instructions, but I can't get any of the Adobe apps to actually run. The crash reports indicate that the apps are indeed still looking for frameworks with wrong-case filenames. My sparsebundle is plain HFS+J; I just double-checked.

My guess? Something changed in Yosemite about how case-insensitive filesystems are referenced while booted from case-sensitive ones, but that's just a wild guess. It might make sense if the missing files were in /Library or ~/Library, but they're not. They're all frameworks inside the actual app bundles.

Another solution I had found used a script to create symlinks for each improperly-referenced filename, but it was for CS5, so some things had changed, and it only had scripts for Photoshop and Illustrator. I tried doing it manually, based on the filenames in the crash reports. I was able to get Photoshop to run that way, but I didn't try to do anything in it, so there still may be references needing fixed later.

I couldn't get Illustrator to run, though. It would launch, but then it brought up a dialog saying "The localized resource files could not be found" and I should reinstall. There weren't any crash reports generated from that, and I couldn't find any relevant log entries either, so I have no idea what specific filenames it was looking for. After that, I didn't bother trying any others.

So I guess I'm looking for ideas. I'm ~20 years out of date in my coding skills, but I'm trying to get back into it. I have a decent understanding of the underpinnings, but putting it into code or shell commands takes more effort because I'm not up to date on the languages. I'm willing to test any solutions you offer, though, and if I do come up with anything that helps, I will of course contribute that.

Once I've come down from my frustrage, I'll give this a try again tomorrow with a new sparsebundle and a fresh install, just to make sure I didn't mess up somewhere. If it works, I'll let you know. But I'm not hopeful.

BTW, I thank you immensely for doing this, even though I'm enraged that it's needed at all. Adobe being unwilling to fix this themselves is proof that the company is run by complete idiots. They have the source code—it would take maybe a couple of person-days to grep all the relevant filename references and make them consistent. You don't even need real coders for that—a few tyros with basic grep skills could handle it. Without the source, we users have to resort to hacks like this, which takes as much time for **each** of us as it would take for them to fix the problem for everyone. They just don't care. Bunch of bassholes.

**Comment by tzvetkoff** [comment]
Hi!

First of all, thanks for the interest and sorry for the late response.

I have a case-insensitive OS X at work right now so I can't test it, so I'll test it later today on my other laptop at home (Yosemite, case-sensitive).

One thing I had to say is that I actually installed CS6 on Yosemite once or twice and it seemed to work properly. I'll check again and give you more details when I have them.

There might be an issue with the CS6 version you're trying to install - if it's updated some thing might break as well. You should also note that the original hack was written for CS5 - I've adapted it for CS6 and it worked for a few years.

**Comment by Quantumpanda** [comment]
Sorry it took so long for me to get back to you on this. I had a minor catastrophe with Amazon Cloud Drive trying to eat my files, which took me most of a week to get resolved. :-( After which, other work was piling up—fortunately, it was work that I could do without CS.

I finally got to try the install again on Thursday. This time, I was able to get it to work, and everything runs as it should. There was a single thing I did differently this time, which may be involved in the problem.

In the hack instructions, you have the sparsebundle created as "Adobe CS6 SparseBundle" as volume name, but the referenced pathname later is /Volumes/AdobeCS6SparseBundle. Now, I am aware that this is how volume names with spaces in them are normally mounted, so I didn't think this was odd.

What was odd was that when I used `mkdir` on that pathname, I was told that I didn't have permission. This struck me as odd, since the volume should have come up with me as owner. The first time I did this, I simply reissued the command as a sudo and continued on. The second time, I did an `ls -l /Volumes/` to see who the owner was, and I found something very interesting (I've included only the relevant part of the output):

```
drwxr-xr-x   6 qpanda  staff  -       272B Apr 29 17:05 Adobe CS6 Runtime/
drwxr-xr-x+  2 qpanda  admin  -        68B Apr 29 17:06 AdobeCS6Runtime/
```

I first noticed that the sparsebundle showed in /Volumes twice, once with spaces and once without. I've never seen this before, though I normally avoid putting spaces in volume names anyway because of peculiarities with how certain apps handled that in earlier versions of OS X. I don't have any others with spaces in the name to check against.

Beyond that, I next noticed that the group assignment was different (every other volume listed with me as owner has "staff" as group), though that shouldn't affect owner's access. Then I noticed that `+`, which of course means there's an ACL attached. `ls -el` revealed:

```
drwxr-xr-x   8 qpanda  staff  -       272B Apr 29 17:59 Adobe CS6 Runtime/
drwxr-xr-x+  2 qpanda  admin  -        68B Apr 29 17:06 AdobeCS6Runtime/
 0: group:everyone inherited deny add_file,add_subdirectory,directory_inherit
```

Now, I have no idea why that ACL is there, but I suspect it was causing the trouble I had. My intuition tells me that the ACL and the different group assignment come from the same source, but I'm lacking the specific knowledge of hdiutil and related functions to figure out why it happened and/or how to prevent it.

So I changed the `mkdir` to reference the pathname with spaces, and got no permissions error. I did the same thing with the symlink later. That seemed to work without any difficulty, and everything runs as expected. So that workaround might be helpful to add to the instructions.

Three other things of interest that might be worth noting in the instructions:

Acrobat X Pro does not get installed in the requested location, but instead as its own folder in /Applications. Fortunately, it also does not appear to have the case-sensitivity issue, as it runs just fine for me. But a heads-up that Acrobat will not be on the sparsebundle image, and that that's okay, would be in order here.

Also, the caution about remembering to mount the sparsebundle image every time you want to run CS seems to me to be the hard way to deal with that issue. I simply added the sparsebundle to my login items, so it automatically mounts when I login, and I have to think about it only if it's been unmounted for some reason. A 15GB sparsebundle image that's mounted but not being accessed, and is excluded from Spotlight indexing, isn't going to create much if any performance hit, so there's little reason to not just have it always mounted.

Finally, as the update in your instructions makes clear, you have to use this again to properly run the updater. Given that, I don't see much reason to delete the working folder at all, unless it's likely that the hack itself will change. I simply kept the sparsebundle and the hack there after the install completed. With the image automounting at login, it doesn't need to be out in the open at all, and keeping the hack around makes running updates simpler. It's not as though it takes up much space. And even though Adobe claims that CS6 has been fully superseded by Creative Cloud, there's always still the chance that more updates to CS6 may come out if any critical security issues are discovered. (And I refuse to use Creative Cloud as long as I have other viable options, just as I refuse to use Microsoft Office 365. I won't pay for a subscription just to keep using the same software without there being an appropriate service also being supplied—and the "cloud storage" offered with these subscriptions isn't worth the cost of the subscription, not when compared to other cloud systems like Google Drive, DropBox, Evernote, or even iCloud.)

Again, thanks for making this available. Until I found this, I was sure that I was going to have to choose between having Creative Suite and having a properly functioning Unix environment. It's always refreshing to find that someone has a solution to my problem, and it's offered freely. This is the true spirit of hacking.

**Comment by tzvetkoff** [comment]
Glad to here you've finally nailed it!

I think, however, that the problem is not related to the spaces, as volumes with space in their names are mounted in directories with spaces:

```
$ ls -l /Volumes
total 8
drwxr-xr-x  6 w00t  staff  272 May  4 15:16 Adobe CS6 SparseBundle/
```

I think that you might've created the `/Volumes/AdobeCS6Runtime` directory and then locked it somehow.

Either way, I'm happy that it's working.

I'll try hacking Creative Cloud at some point, but for now I'm too lazy about it (and I don't want to pay the subscription taxes either)

**Comment by Quantumpanda** [comment]
I don't see how I could have locked it somehow, as I didn't do anything different from your instructions except changing the names of files and directories.

As a test, I tried creating it again, cutting and pasting commands from your instructions. Here is the unedited result:

```
Mon 2015-05-04 04:14:33 PM qpanda in ~ -bash 4.3.33
$ ls -l /Volumes
total 8
drwxrwxr-x@  9 qpanda  staff   510 Apr 29 21:29 Aardvark
drwxr-xr-x   8 qpanda  staff   340 Apr 29 17:59 Adobe CS6 Runtime
drwxr-xr-x+  2 qpanda  admin    68 Apr 29 17:06 AdobeCS6Runtime
lrwxr-xr-x   1 root    admin     1 Apr 29 16:29 Blackbird -> /
drwxr-xr-x@ 41 root    wheel  1462 May  3 01:31 Constitution
drwxrwxr-x@  6 root    wheel   476 Apr 11 17:20 Harrier
drwxrwxrwx   0 root    wheel     0 May  4 16:26 MobileBackups
drwxrwxr-x@ 16 qpanda  staff   952 May  3 01:31 Nighthawk
drwxrwxr-x@ 25 root    admin   918 Apr  9 21:58 Raptor
drwx------  12 qpanda  staff   714 Feb 16 16:33 Secure
Mon 2015-05-04 04:15:03 PM qpanda in ~ -bash 4.3.33
$ mkdir -p ~/Stuff/Adobe
Mon 2015-05-04 04:15:16 PM qpanda in ~ -bash 4.3.33
$ cd ~/Stuff/Adobe
Mon 2015-05-04 04:15:27 PM qpanda in ~/Stuff/Adobe -bash 4.3.33
$ hdiutil create -size 15g -type SPARSEBUNDLE -nospotlight -volname 'Adobe CS6 SparseBundle' -fs 'Journaled HFS+' ~/Stuff/Adobe/Adobe_CS6_SparseBundle.sparsebundle
created: /Users/qpanda/Stuff/Adobe/Adobe_CS6_SparseBundle.sparsebundle
Mon 2015-05-04 04:17:56 PM qpanda in ~/Stuff/Adobe -bash 4.3.33
$ open ~/Stuff/Adobe/Adobe_CS6_SparseBundle.sparsebundle
Mon 2015-05-04 04:18:23 PM qpanda in ~/Stuff/Adobe -bash 4.3.33
$ mkdir -p /Volumes/AdobeCS6SparseBundle/Adobe
mkdir: /Volumes/AdobeCS6SparseBundle/Adobe: Permission denied
Mon 2015-05-04 04:18:41 PM qpanda in ~/Stuff/Adobe -bash 4.3.33
$ ls -el /Volumes
total 8
drwxrwxr-x@  9 qpanda  staff   510 Apr 29 21:29 Aardvark
drwxr-xr-x   8 qpanda  staff   340 Apr 29 17:59 Adobe CS6 Runtime
drwxr-xr-x   6 qpanda  staff   272 May  4 16:18 Adobe CS6 SparseBundle
drwxr-xr-x+  2 qpanda  admin    68 Apr 29 17:06 AdobeCS6Runtime
 0: group:everyone inherited deny add_file,add_subdirectory,directory_inherit
drwxr-xr-x+  2 qpanda  admin    68 May  4 16:18 AdobeCS6SparseBundle
 0: group:everyone inherited deny add_file,add_subdirectory,directory_inherit
lrwxr-xr-x   1 root    admin     1 Apr 29 16:29 Blackbird -> /
drwxr-xr-x@ 41 root    wheel  1462 May  3 01:31 Constitution
drwxrwxr-x@  6 root    wheel   476 Apr 11 17:20 Harrier
drwxrwxrwx   0 root    wheel     0 May  4 16:18 MobileBackups
drwxrwxr-x@ 16 qpanda  staff   952 May  3 01:31 Nighthawk
drwxrwxr-x@ 25 root    admin   918 Apr  9 21:58 Raptor
drwx------  12 qpanda  staff   714 Feb 16 16:33 Secure
Mon 2015-05-04 04:19:02 PM qpanda in ~/Stuff/Adobe -bash 4.3.33
$ 
```

So, on my system, at least, your commands as written produce this ACL. I'm using a newer bash than what Apple provides, but I'm unsure how that might cause this to happen.

And it wasn't the fact that the volume mounted with spaces that I hadn't seen before—it was the volume mounting twice, once with spaces and once without, and those two volumes having different permissions and ownership, that was a surprise to me. Also interesting is that detaching the volume that has spaces in the name with hdiutil does not unmount the one without spaces in the name, and once that first one is unmounted, any terminal command I use to act on that pathname says it can't be found, even though it still clearly shows up in an ls. (I used Path Finder to trash it directly out of /Volumes. I haven't tried removing the unspaced volume first to see if the same thing happens the other way around. That's an investigation for another day.)

For comparison, I mounted a .dmg with spaces in its volume name, and it showed up normally. So it's not the mere fact that it's a volume with spaces in the name—there must be something about how the image is created that causes this.

For the most part, this is probably something in my own setup, not in your hack, so I don't think you need to investigate anything else. I do recommend you either change the hack instructions to reference that volume with the spaces in the name, or add a note to the hack instructions about it, for in case someone else has the same thing happen, so they know **not** to just sudo the mkdir like I did. I'm pretty sure that my overriding the ACL on that volume was what ultimately caused my first install of CS to not run correctly.
