### ISSUE TITLE
Can you improve script for CC versions?

### ISSUE THREAD

**Issue by max-mykhailenko** [tzvetkoff/adobe_case_sensitive_volumes#2]
I want to install Adobe CC 2015 version and got on `sudo make run` the next error 

```
DYLD_INSERT_LIBRARIES=/Users/max/Stuff/Adobe/adobe_case_sensitive_volumes/lib_override_volume_sensitivity_check.dylib /Volumes/CS6*/*/Install.app/Contents/MacOS/Install
/bin/sh: /Volumes/CS6*/*/Install.app/Contents/MacOS/Install: No such file or directory
make: *** [run] Error 127
```

**Comment by max-mykhailenko** [comment]
Set PATH and all works good. Install Illustrator too.

**Comment by malthe** [comment]
@max-mykhailenko set `PATH` to what?

**Comment by max-mykhailenko** [comment]
@malthe Try this `export PATH="/usr/local/sbin:$PATH"` in your bash profile. My current PATH variable contains `/usr/local/sbin:./node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by malthe** [comment]
@max-mykhailenko, what's in your `/usr/local/sbin` – ?

I have nothing in that directory. I was thinking about monitoring the install process to see what file operation leads to it giving up.
